[package]
name = "gaussian"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version="0.8.4" , features = ["multipart"] }
image = "0.25.6"
tokio = { version = "1.44.2" , features = ["rt-multi-thread"] }
